# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
